openapi: 3.0.0
paths:
  /cats:
    post:
      operationId: CatsController_create
      parameters: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/CreateCatDto"
      responses:
        "201":
          description: ""
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/CatDto"
    get:
      operationId: CatsController_findAll
      parameters: []
      responses:
        "200":
          description: ""
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/CatDto"
  /cats/owners:
    get:
      operationId: CatsController_findCatOwners
      parameters: []
      responses:
        "200":
          description: ""
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/UserDto"
  /cats/{name}:
    get:
      operationId: CatsController_findOneCat
      parameters:
        - name: name
          required: true
          in: path
          schema:
            type: string
      responses:
        "200":
          description: ""
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/CatDto"
info:
  title: Cats example
  description: The cats API description
  version: "1.0"
  contact: {}
tags:
  - name: cats
    description: ""
servers: []
components:
  schemas:
    CreateCatDto:
      type: object
      properties:
        name:
          type: string
        age:
          type: number
        breed:
          type: string
      required:
        - name
        - age
        - breed
    CatDto:
      type: object
      properties:
        name:
          type: string
        age:
          type: number
        breed:
          type: string
      required:
        - name
        - age
        - breed
    UserDto:
      type: object
      properties:
        id:
          type: number
        email:
          type: string
        first_name:
          type: string
        last_name:
          type: string
        avatar:
          type: string
      required:
        - id
        - email
        - first_name
        - last_name
        - avatar
