services:
  first-project:
    build:
      context: ../../
      dockerfile: ./apps/first-project/Dockerfile
    image: 'docker-phil-sahi.pruregistry.intranet.asia:8443/first-project'
    container_name: first-project
    ports:
      - "8080:8080"
    environment:
      - NODE_ENV=production

  pubsub-emulator:
    image: docker-phil-sahi.pruregistry.intranet.asia:8443/cloud-sdk-emulator:latest
    container_name: pub-sub-emulator
    ports:
      - "8085:8085"
    command: gcloud beta emulators pubsub start --project=sample-project --host-port=0.0.0.0:8085

  postgres:
    image: docker-phil-sahi.pruregistry.intranet.asia:8443/postgres:latest  # Use the latest official PostgreSQL image
    container_name: postgres-db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=qwerty
      - POSTGRES_DB=first-project
    volumes:
      - postgres-data:/var/lib/postgresql/data  # Persist data outside the container
    ports:
      - "5433:5432"  # Expose PostgreSQL on port 5432

  first-project-dev:
    build:
      context: ../../
      dockerfile: ./apps/first-project/Dockerfile
      target: development
    image: 'monorepo/first-project'
    container_name: first-project-dev
    ports:
      - "8080:8080"
    develop:
      watch:
        - path: ./src
          action: rebuild
        - path: ../../package.json
          action: rebuild
    environment:
      - PUBSUB_EMULATOR_HOST=pubsub-emulator:8085
      - PUBSUB_PROJECT_ID=sample-project
      - NODE_ENV=development
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=qwerty
      - POSTGRES_DB=first-project
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
    depends_on:
      - pubsub-emulator
      - postgres

volumes:
  postgres-data: