name: Build nestjs project
run-name: Build running for path - ${{ github.event_path }}
on:
  push:
    paths:
      - apps/first-project/**

jobs:
  build-docker:
    runs-on: ubuntu-latest
    steps:
      - name: Docker login
        run: docker login docker-phil-sahi-local.pruregistry.intranet.asia:8443 -u ${{ secrets.ARTIFACTORY_SERVICE_ACCOUNT }} -p ${{ secrets.ARTIFACTORY_SERVICE_ACCOUNT_PASSWORD }}
      - name: docker compose up
        run: docker compose build -f apps/first-project up first-project
      - name: docker images ls
        run: docker image ls
