name: Build nestjs project
run-name: Build running for path - ${{ github.event_path }}
on:
  push:
    paths:
      - apps/first-project/**

jobs:
  build-docker:
    runs-on: ubuntu-latest
    environment: development
    steps:
      - name: checkout repo
        uses: actions/checkout@v4
      - name: docker compose up
        run: docker compose -f apps/first-project build first-project
      - name: docker images ls
        run: docker image ls
