name: learn github actions
run-name: ${{ github.actor }} is learning github actions
on:
  push:
jobs:
  print-name:
    runs-on: ubuntu-latest
    env:
      NAME: Akash
    steps:
      - name: Print and setting name

        run: |
          echo $NAME
          NAME='Kirti'

      - name: Print reset variable
        run: echo $NAME

  print-current-files:
    runs-on: ubuntu-latest
    steps:
      - name: Print files
        run: ls

  checkout-and-print:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: print files
        run: ls
