name: learn github actions
run-name: ${{ github.actor }} is learning github actions
on:
  push:
    paths:
      - ./apps/**
jobs:
  print-name:
    runs-on: ubuntu-latest
    steps:
      - name: Print a greeting
        env:
          MY_VAR: Hi there! My name is
          FIRST_NAME: Akash
          LAST_NAME: Manoj
        run: echo $MY_VAR $FIRST_NAME $LAST_NAME.

  check-bat-version:
    runs-on: ubuntu-latest
    steps:
      - name: Use actions
        uses: actions/checkout@v4
      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install bats
        run: npm install -g bats
      - name: Run bats
        run: bats -v
